### PR TITLE
Zoom orientation

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
This PR addresses the issue with the variant track not being updated by the zoom track, and recalculates the gene strand orientation on zoom.  This branch was originally merged into dev, and has been updated to include only the relevant changes for fixing the zooming/orientation issues in branch 4.2.3

 I chose to include the switchover to using the version of phenolyzer running on the new backend, but I am happy to remove this if we don't want this change on production yet, or if we don't want any unrelated changes included in this PR.

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://f032f059.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://4bf09d3e.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://5c2084dc.quarantest.iobio.io

**Comment by mvelinder** [comment]
Testing on the quarantest build above and the demo data...

It looks like the selected variant is not retained when using the zoom feature.

Select a variant in the track by clicking on it, variant is selected
image

Toggle zoom to on, variant is still selected
image

Drag to zoom on the exon, variant selection is lost
image

I'm not sure if this was always how it worked or if it has since broken, but let's get it fixed regardless

**Comment by mvelinder** [comment]
Made a new issue for this on Release planning board. Current state is good for now

**Pull request merged**
