### PR TITLE
adding navigation back to homepage with warning navigation gaurds

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Adding a link to  gene.iobio title  back to homepage with navigation guard

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://6c9076f5.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test, open up the quarentest link.

1) when clicking on the gene.iobio title from the home screen, nothing should happen.
2) Launch with demo data and click on the gene.iobio title again. You should see a confirm dialog appear warning the user about the consequences (On quarentest you may have to wait until you close out the Omim aler to see this alert)
3) When selecting cancel, no rerouting should occur
4) When selecting OK, you should return to the homepage

**Review by adityaekawade — COMMENTED** [review]
This works fine..
But I think instead of clearing the analysis, we can still allow the users to go to the homepage and then resume the analysis. 

For example, when the "gene.iobio" link is clicked, `showWelcome` flag in `GeneHome.vue` sets to true. This should show the `<Welcome.vue>` component, which has the content for the landing page. 

Now, if the analysis is in progress, the buttons on the `Welcome.vue` can be replaced to show "Resume analysis" or "Start a new analysis". 

Clicking the "Resume Analysis" should again set the  `showWelcome` flag in `GeneHome.vue` to false and return back to the analysis. If "start new analysis" is clicked, it can refresh the page with `window.location.href= '/'`.

**Comment by WilliamRichards2017** [comment]
@adityaekawade Really good call, I didn't know I would be able to do that.  I'll get those changes implemented, thanks!

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://4260d4d5.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://8523e53c.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://9e51d8e9.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
@adityaekawade This PR has been updated to implement the resume analysis functionality that Clin has.

**Review by adityaekawade — APPROVED** [review]
Looks great! :thumbsup:

Screen Shot 2020-09-17 at 2 05 13 PM

**Pull request merged**
