### PR TITLE
Grch38

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
This pull request addresses issues with grch38 transcripts and data state management on transcript change.  We have decided that the unknown impact of variants for specific transcripts is expected behavior, as these variants do not fall within a coding region, and are not important regulators.

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://838e3d98.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://9ae710b5.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://a2137c8c.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test: go to http://a2137c8c.quarantest.iobio.io/?gene=COL9A3&genes=COL9A3&species=Human&build=GRCh38&affectedSibs=&unaffectedSibs=&rel0=proband&vcf0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fvcf%2Fplatinum-exome.GRCh38.vcf.gz&tbi0=&bam0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fbam%2FNA12878.GRCh38.bam&bai0=&sample0=NA12878&affectedStatus0=affected.  

1. Select the farthest left variant from the default canonical transcript
2. Click the transcripts dropdown - There should be no weird empty whitespace, and the transcript dropdown should appear normal.
3. Select the top transcript (463487.2) - The initially selected variant should be retained, and the variant card should be updated to reflect the updated transcript. There should be no gray symbols in the pathogenicity card without any text. 
4. Select the legend dropdown - You should see a gray 'unknown' key under the impact legend.

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://90a6ee10.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://843a6415.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test: go to http://843a6415.quarantest.iobio.io/?gene=COL9A3&genes=COL9A3&species=Human&build=GRCh38&affectedSibs=&unaffectedSibs=&rel0=proband&vcf0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fvcf%2Fplatinum-exome.GRCh38.vcf.gz&tbi0=&bam0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fbam%2FNA12878.GRCh38.bam&bai0=&sample0=NA12878&affectedStatus0=affected

Select the farthest left variant from the default canonical transcript
Click the transcripts dropdown - There should be no weird empty whitespace, and the transcript dropdown should appear normal.
Select the top transcript (463487.2) - The initially selected variant should be retained, and the variant card should be updated to reflect the updated transcript. There should be no gray symbols in the pathogenicity card without any text.
Select the legend dropdown - You should see a gray 'unknown' key under the impact legend.

**Review by adityaekawade — COMMENTED** [review]
I get the warning `Unable to access OMIM. API key is required in env.` when I am testing it on quarantest.

**Review by adityaekawade — COMMENTED** [review]
Tested on quarantest. Look good!
Screen Shot 2020-09-15 at 1 59 38 PM
Screen Shot 2020-09-15 at 2 00 24 PM

**Pull request merged**
