### PR TITLE
Internal endpoints

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
refactoring mosaic api endpoint from apiv1/ to api/v1/
Removing endpoint for client-application, grabbing client-application-id from url params

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://992fd7d5.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test:

verify that all endpoints use the api/v1/ route
verify that no requests to apiv1/client-applications or api/v1/client-applications have been made

**Comment by WilliamRichards2017** [comment]
> Hi Will -
> I noticed this pull request has conflicts that need to be merged. Can you merge this today so that dev has this change? I'm meeting with Timothy and Al and FS tomorrow and want to make sure I'm working off of the latest REST API for Mosaic. Thanks! Tony

sure!

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://ad7aed13.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://2d2ebbdf.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://51225d20.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://5601bb5c.quarantest.iobio.io

**Pull request merged**
