### PR TITLE
User upload fix

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Fixing issue with user uploaded vcfs not being error checked properly, fixing user upload error checking to allow only a vcf.

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://a5713403.quarantest.iobio.io

**Comment by stefinfection** [comment]
Bam only local upload working correctly; vcf only local upload working correctly; only suggestion is that when bam only is loaded, you still display 'Proband variants' track and it's just empty - may as well hide it if no vcf uploaded

**Comment by stefinfection** [comment]
Also, read pileup doesn't work for local file upload or presigned S3 URLs (by design). You may want to hide that link when either of those upload formats are used

**Comment by WilliamRichards2017** [comment]
Merging the fix and opening separate issues to how we want to handle bam only / user upload display and functionality

**Pull request merged**
