### PR TITLE
removed VariantInterpretationbadge rectangle from variant card when n…

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Removed unwanted rectangle from variant review panel when a note is added but the variant is flagged as not reviewed.  Let me know whenever you're ready to test this and I can fire up an ngrok instance

### CODE REVIEW

**Comment by tonydisera** [comment]
@WilliamRichards2017, I think this bug fix may have introduced new behavior.  Variants that have notes (but no interpretation) are supposed to show up in the Findings page of clin (I think).  Although I'm not sure how this was implemented.  Can you please coordinate with Matt and Adit on this?

**Comment by WilliamRichards2017** [comment]
Yeah for sure, I'll look into that!

**Comment by WilliamRichards2017** [comment]
@tonydisera @adityaekawade I did some testing on this, and there seem to be issues with any reviewed variants appearing in the findings page when clin is using Mosaic data.  I tested this on a dev branch without the changes, and on this PR branch, and saw the same behavior on the findings page.  When I tested this PR with clin demo data, not reviewed variants with a note added appeared in the findings page as unknown significance.  I recommending merging this pull request and opening up a new issue in clin about reviewed variants not displaying in the findings page.  I'm happy to take the lead on this and add the issue if you both are in agreement!

**Comment by adityaekawade** [comment]
Hi @WilliamRichards2017 
I noticed that any reviewed variant is not shown on the findings page when clin.iobio is launched from Mosaic. Works fine in standalone mode. We can tackle these behaviors in a separate issue and close this PR if it fixes its respective issue.

**Comment by tonydisera** [comment]
If you can put the issue number in the pull request, that would save me a bit of time.

**Comment by WilliamRichards2017** [comment]
My bad, I'll make sure to attach the issue to the pull request next time

**Pull request merged**
