### PR TITLE
Use cacheable endpoints

### PR DESCRIPTION
**Pull request by anderspitman**

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://cdc51443.quarantest.iobio.io

**Comment by anderspitman** [comment]
Looks like there are some CORS issues with CloudFront that I'll need to resolve before we review this.

**Comment by anderspitman** [comment]
@tonydisera I believe this is ready for review. It updates gene to take advantage of cached versions of /geneinfo and /gene2pheno.

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://54c25e19.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://54c25e19.quarantest.iobio.io

**Comment by tonydisera** [comment]
Looks good.

**Comment by tonydisera** [comment]
Read to merge PR.

**Pull request merged**
