### PR TITLE
Obvious file input

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Changed terms of service glyph, added file upload icon to navigation toolbar, added upload data button on welcome page

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://776acfd7.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test:
1) launch from quarentest
2) Click the terms of service icon and make sure you see the TOS popout
3) Press the upload data button on the welcome screen.  Apply the WES/WGS demo data button.  Enter a gene to make sure that the app is behaving as expected
4) Go back to the welcome page, and upload data with the upload icon on the navigation bar.  Enter a gene to make sure the app is behaving as expected

**Comment by mvelinder** [comment]
Looks good to me!

**Comment by adityaekawade** [comment]
Hi @mvelinder , @WilliamRichards2017 . It looks great, but just a small suggestion. I think the icon used here for the upload, is actually a download icon.

**Comment by tonydisera** [comment]
The terms of service icon looks like a security warning. Do we really need this in the nav bar?  Also, make sure the positioning works w the Mosaic save button. I worry that the nav bar is getting cluttered again.

**Comment by WilliamRichards2017** [comment]
> Hi @WilliamRichards2017 , @mvelinder . It looks great, but just a small suggestion. I think the icon used here for the upload, is actually a download icon.

Good catch, I'll change it to an upload icon!

**Comment by WilliamRichards2017** [comment]
> The terms of service icon looks like a security warning. Do we really need this in the nav bar? Also, make sure the positioning works w the Mosaic save button. I worry that the nav bar is getting cluttered again.

Ill Make sure the position works with the new save button in the nav bar.  And I don't think that we need the terms of service in the nav bar.  I'm more than happy to remove it if everyone is okay with that. I can ask Al and Matt on there thoughts for removing the terms of service glyph from the nav bar

**Pull request merged**
