### PR TITLE
Review n genes

### PR DESCRIPTION
**Pull request by adityaekawade**
PR for new feature (https://github.com/iobio/clin.iobio/issues/252) in clin.iobio

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://59697257.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://5542a534.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://ff7196bc.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
Looks good and appears to work as expected. One thing I noticed is that I only added the top 10 genes, but the alertify warning said that 17 genes would be added, which was confusing. I might also add the ability to toggle the add N genes button to add/remove the genes, so its a little bit more clear what happens when you press that button. I was a bit unsure on the first test if pressing the button added the genes, although the icon change was clear to me the second time testing. These are minor issues, and I'm happy to approve if you wanna address these small things separately. Overall looks very good, and the functionality is there.

**Review by WilliamRichards2017 — APPROVED** [review]
Functionality looks good, and the only suggestions to the PR are on the clin side of things

**Pull request merged**
