### PR TITLE
Review n genes

### PR DESCRIPTION
**Pull request by adityaekawade**

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://10bec8c5.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://201224f2.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://37ccf043.quarantest.iobio.io

**Review by WilliamRichards2017 — APPROVED** [review]
Looks good to me! I like the new visual for the percent of genes selected, but this could cause some confusion to new users.  It might benefit from a label or a tooltip!

**Pull request merged**
