### PR TITLE
Clin var reload fix

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Prevents the re-rendering of variant tracks when optianalTracks menu is close, check if data changed in a meaningful way when updating variant-viz

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://aecf63fd.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://1cc8b2ca.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
Available for final testing at http://1cc8b2ca.quarantest.iobio.io

To test - validate that tracks are no-longer re-rendered when the clinVar track is selected, or when optional tracks menu is closed.

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://dd2ead3d.quarantest.iobio.io

**Pull request merged**
