### PR TITLE
Disable filters

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Removed ability to add custom filters, made existing filters uneditable

### CODE REVIEW

**Comment by tonydisera** [comment]
We need a couple more changes to make filters read-only.
1.  Let's change the pencil icon to info (outline)
Screen Shot 2020-03-31 at 8 12 33 PM
Screen Shot 2020-03-31 at 8 15 02 PM
2. Remove 'Edit' from the title and remove the 'Cancel' button, and hide the 'Apply' button.
Screen Shot 2020-03-31 at 8 12 26 PM

**Comment by WilliamRichards2017** [comment]
sounds good!

**Comment by WilliamRichards2017** [comment]
These changes have been implemented and the PR is ready to be re-reviewed

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://82d12dde138c02e922982414b98d5ec0473becc2.quarantest.iobio.io

**Comment by will** [comment]
cool, yeah go for it!

**Comment by mvelinder** [comment]
This looks sufficiently addressed to me after testing on the quarantest build

**Pull request merged**
