### PR TITLE
Gene viz exon coverage

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Update gene-viz exon coverage warning glyph on coverage threshold change.  Fixed bug where gene-viz was displaying warning glyph values for proband on otherTracks

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://71ede105.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
@tonydisera @anderspitman I'm seeing some weird behavior when testing this on quarentest.  When the gene-viz is rendered, it is not always properly updated. I'm seeing these console errors when testing only inside quarentest, but everything looks normal when testing locally.  It looks like quarentest is struggling to decompress the cache.  I would recommend doing a local install to test this PR.  Let me know if you have any questions or run into any issues testing locally!
Screen Shot 2020-04-09 at 5 07 25 PM

**Comment by tonydisera** [comment]
Hi Will.  This functionality is fixed!  Thank you.   One little thing is that it would be good to refresh the current gene when the new coverage cutoffs are applied.  That way the glyphs on the current gene would refresh without the user having to click it again.  Do you want me to submit a new issue?  I'll mark this pull request as approved and you can decide if you want to keep it open.  Thank you! - Tony

**Comment by anderspitman** [comment]
@WilliamRichards2017 now that this is merged can you check staging and verify you're no longer getting that error? They're might be additional differences in the way the quarantest server is hosting the files.

**Pull request merged**
