### PR TITLE
Not changing users focus to first flagged variant if user selects a gene

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
first flagged variant will only be selected if user is on that gene, otherwise, the user will stay on the gene, and the variants tab will be selected to show the analyzed variants.  needs to be tested from clin and saved analysis

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://f82c4b12.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test:
1) Load with demo data.  Let the data load, and do not select another gene.  The first flagged variant should be selected.
2) Load again with demo data.  This time, select another gene to examine while the data is loading.  When the analysis is finished, the variants tab should pop up, but the first flagged variant should not be selected, and the user should remain on the gene they were looking at.

**Review by adityaekawade — APPROVED** [review]
Looks good! The focus stays on the selected gene when the tab is switched from gene to variant. 
If gene is not selected the first flagged variant is selected.

**Comment by adityaekawade** [comment]
I noticed, that if I select a variant from the variants tab.. It is selected at first, but once the variant is analyzed it loses its focus. 
For example: 
Screen Shot 2020-10-01 at 4 58 27 PM
Should there be a focus on PDGFB variant in the left sidebar since it is currently selected?

**Comment by AlistairNWard** [comment]
Looks good @WilliamRichards2017.

I don't see the losing focus that @adityaekawade noted above. There isn't any focus in the left menu if you have selected a variant from it in gene in general. This might be worth adding though. If you select a variant from the left menu, there would be value in keeping an indicator in the left menu that the variant is selected. If you selected the variant in the main track, that would then also cause the variant to be highlighted in the left menu. That would be a different issue though

**Comment by WilliamRichards2017** [comment]
@AlistairNWard 

I totally agree, and was planning to address that as well in a separate issue.  I'll open up a new issue to have the selected variant always highlighted in both the variant track and the left panel (if it exists there)

**Comment by AlistairNWard** [comment]
Cool. Would be worth thinking about the best way to represent the highlighted variant in the left menu. A standard material design coloured bar over the variant might be too much given all our glyphs, and another glyphs would probably not be clear enough. Maybe some little indicator to the left of the variant to point at the selected one?! Anyway - a different issue!

**Pull request merged**
