### PR TITLE
fix-associated genes not showing in clin.iobio

### PR DESCRIPTION
**Pull request by adityaekawade**
This Pull request should fix the following issue in clin.iobio repo: https://github.com/iobio/clin.iobio/issues/131

Testing steps: 
Use the branch fix-gene-association 

**Standalone mode**: 

1. Launch clin.iobio (localhost:4030) and load with demo data. 
2. Go to step 2 (select phenotypes) and submit the example note.
3. Select the condition (ex. Dejerine sotas disease) and phenotypes (ex. charcot marie tooth disease and dejerine sotas disease) and generate the gene list 
4. Go to step 3 (Review variants). Variant PRX should show Gene Associations (See screenshot). The current version of clin.iobio is not showing any gene associations.  
5. Mark the variant as significant
6. Go to step 4 (Report findings). Gene association should be shown for gene PRX. 

 
Screen Shot 2020-04-02 at 2 51 57 PM

**Launch from Mosiac** 
Select MPPH case and launch clin.iobio 
Go to step 2 (select phenotypes) and enter the condition (ex. **hydrocephalus**) as input 
Select the condition (ex. hydrocephalus) and phenotypes (ex. hydrocephalus) and generate the gene list
Go to step 3 (Review variants). Variant CCND2 should show Gene Associations 
Save the analysis 
Go to the Analysis tab in Utah Mosaic 
Select the saved analysis and launch Mosaic 
Go to step 3 and verify that Gene association is shown for the variant CCND2.

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://f90141ee019cfe0e086b39163e6a7a3961216c08.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
Tested this and the gene associations, and saved analysis appear correct to me

**Comment by adityaekawade** [comment]
Hi @tonydisera , 

Related issue: https://github.com/iobio/clin.iobio/issues/131 

@WilliamRichards2017  and I have tested its behavior by following the steps outlined in the description and seems to be working as expected.

**Comment by mvelinder** [comment]
Yes, was fixed in my clin testing

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://f90141ee.quarantest.iobio.io

**Pull request merged**
