### PR TITLE
Legend rework

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Legend rework rough draft

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://d24e0826.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://30d24eb6.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://371d2d6d.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://82f82ed4.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://d2dbd6a8.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
@mvelinder @adityaekawade @AlistairNWard  Hi guys, this PR contains the majority of legend rework revisions contained in this thread: https://marthlab.slack.com/archives/G015S8KCV52/p1604350825009300

There are a few loose ends to tie up.  I have listed these below and tagged all relevant parts of the codebase with todo's.
Legend Rework todo:

1) Review/improve legend info popup descriptions.  These descriptions can be found in the ‘partials/InfoPopup.vue’ file, and have been marked with a  'check' or 'improve' //todo: comment

2) Change Recessive glyph to autosomal recessive glyph.  The place replace this glyph is tagged with //todo: in ‘partials/AppIcon.vue’

3) Figure out categorization criteria for Pathogenic evidence glyphs.  Right now, pathogenic evidence badges, i.e. strong evidence, moderate evidence, are colored based on the no longer used checkmark badge class.  In ‘partials/VariantInspectRow.vue’, there is a stub class tagged with //Todo:, that needs to assign a Pathogenic Evidence impact to the glyph, based on the content of the evidence, rather than the less informative ‘class value’.

**Review by adityaekawade — APPROVED** [review]
Looks good. I can see the description and icons added/ updated at several places.

**Comment by adityaekawade** [comment]
Thanks, @WilliamRichards2017  for adding the ToDo comments, makes it clear what needs to be added!

**Comment by AlistairNWard** [comment]
I haven't had time to go through all the popup descriptions, but I'll keep adding to this comment as I look through. If you find

- [ ] RAI1 variant shows the strong evidence for pathogenicity glyph in the Conservation section. We don't show anywhere what the criteria are for showing this glyph though. We should make sure that the user can find the criteria for these glyphs everywhere they are used. For example, we should have an info tooltip next to conservation and include the values for these criteria there.

**Pull request merged**
