### PR TITLE
Margin and button styling

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Fixed wide margin and styled gene panel 'Analyze all', 'stop analysis', and 'Call variants' buttons

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://81bdcce91bae215d61fe84fcb68fe8fdfa508c0c.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
To test this, you should see the 'Analyze all' and 'Call variants' buttons styled like the image below
Screen Shot 2020-04-07 at 5 40 47 PM

**Comment by WilliamRichards2017** [comment]
The margin should also be smaller, and appear like the image below
Screen Shot 2020-04-07 at 5 42 23 PM

**Comment by tonydisera** [comment]
@WilliamRichards2017 , please put the issue number in the pull request.

**Pull request merged**
