### PR TITLE
Transcript fix

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Fixed empty transcript menu, added gene-viz when only gene entered, added gene-viz to other model tracks, showExon now displays correctly for other tracks, added terms of service glyph to nav bar, only drawing gene-viz once, and updating when data changes,

### CODE REVIEW

**Comment by WilliamRichards2017** [comment]
This pull request has been updated with the recommended changes after review

**Comment by mvelinder** [comment]
@WilliamRichards2017 is this deployed somewhere I can test it? dev.gene.iobio.io?

**Comment by WilliamRichards2017** [comment]
deployed to http://25e8c9ec.ngrok.io/

**Comment by mvelinder** [comment]
Looks good to me for merging

**Comment by tonydisera** [comment]
@WilliamRichards2017 @mvelinder  
Screen Shot 2020-03-26 at 5 38 02 PM
I am going to merge this pull request, but we still have problems with showing the correct coverage for Mother and Father exons.  I'll create a new issue.

**Pull request merged**
