### PR TITLE
dynamically updating region bugger width

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Dynamically resizing up/downstream region to accommodate for larger regions

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://1ef951b8.quarantest.iobio.io

**Comment by AlistairNWard** [comment]
I think I'd prefer a fixed size approach, unless the dynamic resizing can take place in real time. The reason it's important to see what you're typing as you type. For example, once you've exceeded the size of the box, you can no longer see what you've put in, and now I don't know if I've put in too many zeroes:

Screen Shot 2020-08-13 at 5 05 30 PM

I can either delete and start again, or click off it to have the box resize, but this also triggers recalculating variants etc:

Screen Shot 2020-08-13 at 5 05 36 PM

**Comment by AlistairNWard** [comment]
Also - region bugger width?!?!

**Comment by WilliamRichards2017** [comment]
Happy to re-do this with a fixed width, and maybe cap the region buffer size.  How does that sound to you
 @mvelinder

**Pull request merged**
