### PR TITLE
adding empty variant to intersectedGenes if gene contains no variants

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
This fixes clin hanging when there is a gene in the geneList with no variants.  The issue was caused by the gene not being added to the intersectedGenes list, so the gene is added with a null variant

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://cf2a8f3a.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://4fcdaa84.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://7755e14c.quarantest.iobio.io

**Comment by adityaekawade** [comment]
Working fine with custom data and the badge is showing correct variants count.

**Pull request merged**
