### PR TITLE
updated vue-pileup to newest version of igv.js

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
@mvelinder  Updated vue-pileup to use newest version of igv.js

### CODE REVIEW

**Comment by anderspitman** [comment]
Here's the test URL for this PR: http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io/

**Comment by anderspitman** [comment]
@WilliamRichards2017 when launching the external IGV, it looks like all of the indexUrls (VCF and bams) are null

**Comment by anderspitman** [comment]
Hi there

**Comment by anderspitman** [comment]
quarantest build started

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at

http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io

**Comment by mvelinder** [comment]
Working for me on quarantest with the demo data

**Comment by anderspitman** [comment]
@mvelinder are you seeing the weird empty space near the top of gene?

**Comment by anderspitman** [comment]
I'm still seeing indexUrl not populated when launching external IGV

**Comment by mvelinder** [comment]
Yes, @anderspitman I'm seeing the big weird bar too

**Comment by mvelinder** [comment]
I do NOT see this big gray bar on local testing though
image

Seems like a quarantest specific problem, I'd vote to merge and push to stage and then confirm IGV is fixed on stage and this gray bar is not there.

**Comment by anderspitman** [comment]
Yeah it's somehow related to how quarantest does the build. Super weird. What commands did you run to build locally? Also what version of node?

**Comment by mvelinder** [comment]
> Yeah it's somehow related to how quarantest does the build. Super weird. What commands did you run to build locally? Also what version of node?

Not sure, but basically did this:
```
git clone https://github.com/WilliamRichards2017/gene.iobio.vue.git
cd gene.iobio.vue/
git checkout 0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e
npm install
npm start
```

Output from `npm start` was:
```
npm WARN npm npm does not support Node.js v10.17.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> gene-iobio-vue@0.0.0 start /home/matt/Public/tmp/gene.iobio.vue
> DEBUG=http ./node_modules/nodemon/bin/nodemon.js --inspect --ignore client/ www.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --inspect www.js`
Debugger listening on ws://127.0.0.1:9229/07b040c0-9fc5-496a-96b7-ca184557859f
For help, see: https://nodejs.org/en/docs/inspector
  http Express server listening on port 4026 +0ms
  http Listening on port 4026 +1ms
```

Then did `npm run webpack`
```
npm WARN npm npm does not support Node.js v10.17.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> gene-iobio-vue@0.0.0 webpack /home/matt/Public/tmp/gene.iobio.vue
> ./node_modules/webpack/bin/webpack.js --watch

clean-webpack-plugin: /home/matt/Public/tmp/gene.iobio.vue/client/dist has been removed.

Webpack is watching the files…

Hash: acddb5dcf44943c136a5
Version: webpack 2.7.0
Time: 17040ms
   Asset     Size  Chunks                    Chunk Names
build.js  44.3 MB       0  [emitted]  [big]  app
   [4] (webpack)/buildin/global.js 509 bytes {0} [built]
   [6] ./~/vue/dist/vue.runtime.esm.js 227 kB {0} [built]
  [10] ./~/uiv/dist/uiv.esm.js 124 kB {0} [built]
  [45] ./client/app/routes.js 5.97 kB {0} [built]
  [54] ./client/app/globals/GlobalApp.js 10.9 kB {0} [built]
  [55] ./client/app/globals/Util.js 38.1 kB {0} [built]
  [72] ./client/app/partials/GlobalEduTour.js 2.25 kB {0} [built]
 [234] ./~/d3/d3.js 338 kB {0} [built]
 [276] ./~/v-tooltip/dist/v-tooltip.esm.js 120 kB {0} [built]
 [277] ./~/vue-analytics/dist/vue-analytics.js 15.8 kB {0} [built]
 [278] ./~/vue-js-modal/dist/index.js 26.5 kB {0} [built]
 [279] ./client/app/App.vue 1.8 kB {0} [built]
 [398] ./~/vue-router/dist/vue-router.esm.js 65.6 kB {0} [built]
 [480] ./~/vuetify/dist/vuetify.js 1.1 MB {0} [built]
 [483] multi ./client/app/routes.js 28 bytes {0} [built]
    + 469 hidden modules
```

**Comment by mvelinder** [comment]
Problems with project 39 launched from Mosaic

image

**Comment by anderspitman** [comment]
@mvelinder does it work if you replace stage.gene with the quarantest link?

**Comment by anderspitman** [comment]
@tonydisera I think this is good to merge. I tested and verified indexUrl is properly being set, at least when launched from Mosaic.

**Comment by mvelinder** [comment]
> @mvelinder does it work if you replace stage.gene with the quarantest link?

Not sure what you mean. But I'd vote to merge.

**Comment by anderspitman** [comment]
> > @mvelinder does it work if you replace stage.gene with the quarantest link?
> 
> Not sure what you mean. But I'd vote to merge.

The URL hack trick. So you launch from Mosaic, then look in your browser history. Grab the URL with the access token. Paste it into your address bar, and replace https://stage.gene.iobio.io with http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io and load

**Comment by mvelinder** [comment]
> > > @mvelinder does it work if you replace stage.gene with the quarantest link?
> > 
> > 
> > Not sure what you mean. But I'd vote to merge.
> 
> The URL hack trick. So you launch from Mosaic, then look in your browser history. Grab the URL with the access token. Paste it into your address bar, and replace https://stage.gene.iobio.io with http://0e5b4c26572583a4ca7fc29a0cd3c3fcfecdff8e.quarantest.iobio.io and load

I tried that and it never really loaded anything. Let's just merge it

**Comment by anderspitman** [comment]
Good with me.

**Comment by mvelinder** [comment]
Yes, agreed @tonydisera . There needs to be a more clear connection between the issues and the request. The issue is #367

**Comment by mvelinder** [comment]
@tonydisera is this deployed onto dev.gene.iobio.io? I'm testing now on dev, [project 39](18-09-24_VAR-Botto-Complex_Cardiovascular), gene is NPR1 launched from Mosaic, which was our broken test case, **and the issue still appears broken, and sporadic**

Examples:
broken
image

click to another variant in same gene, load it's pileup view, then click back to the original variant, and it's fixed
image

load a different gene, GFI1 and click a variant, load its pileup and it's broken again with a different error/failure **and** you're not able to close the window out so you're basically forced to refresh entirely or relaunch
image

I'm not sure what else I can do in testing. It seems a developer needs to very critically test and debug this to identify the core issue causing it. Our approach so far clearly isn't working. @WilliamRichards2017 can you drive this to completion and resolve the issue?

**Comment by mvelinder** [comment]
@WilliamRichards2017 and @anderspitman , @tonydisera specified that this fix is deployed on stage, not dev. Sorry for the previous message and my confusion on the deployment.

I tested the same project 39 from Mosaic launching and it appears to be fixed!

image
image

I will go ahead and close this issue and consider the final review complete.

**Pull request merged**
