### PR TITLE
User upload error handling

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Warns/prompts user if any of the following cases are detected before loading data from user upload:
1). duplicate family ids
2) duplicate Bam files
3) index files don't match base file path when using URL input instead of file select
4) file extensions don't correspond to expected values (.bam, .bai, .vcf, .tbi, .gz ) when using URL input

### CODE REVIEW

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://401531ba.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://762f8825.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://ac1b9030.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
> Tested for the above mentioned checks. Works very well for error checking!
> Screen Shot 2020-08-06 at 9 26 16 AM
> 
> But I feel, the user should not be allowed to continue and the errors should be corrected. @mvelinder @WilliamRichards2017
> 
> Example when continued with the error:
> Screen Shot 2020-08-06 at 9 31 13 AM

Weird, when I tried to replicate that behavior with continuing with duplicate sample ids it appeared to be working. 
Screen Shot 2020-08-06 at 11 01 36 AM

 I definitely think it makes sense to not allow the user to continue.  The main reason I decided to let the user continue is in the case where the user has some files somewhere on s3 that arent named with a .bam extension or something, and they don't have permission to rename the files. We could also decide to allow the user to continue on certain errors, but require a change for others.  Maybe this is something we could briefly discuss during the next iobio meeting. I'll send you a message on slack @adityaekawade to try and replicate what your seeing with the duplicate ids not loading

**Comment by adityaekawade** [comment]
Oh sorry! Actually it was this condition that had caused the error. 
Screen Shot 2020-08-06 at 9 28 53 AM

> The main reason I decided to let the user continue is in the case where the user has some files somewhere on s3 that arent named with a .bam extension or something, and they don't have permission to rename the files

That's a good point. Maybe we can allow users to continue if the file extensions are missing, but if there are duplicate sample ids or the BAM files do not match with the associated sample ids, we should not let them continue.

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://1af577f3.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://cdda59c2.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://9a951ae5.quarantest.iobio.io

**Comment by tonydisera** [comment]
This error checking is causing a problem because the URL for the tbi can be different than the vcf:

3) index files don't match base file path when using URL input instead of file select

I'm going to remove this validation check.

**Pull request merged**
