### PR TITLE
Filter bug fixes

### PR DESCRIPTION
**Pull request by WilliamRichards2017**
Issues addressed in this PR:
1) Custom filter title not displaying: https://github.com/iobio/gene.iobio.vue/issues/384
2) Cannot delete custom filter: https://github.com/iobio/gene.iobio.vue/issues/385
3) Creating a new filter removes assigned significance inside clin: https://github.com/iobio/gene.iobio.vue/issues/390
4) All attributes can be removed from a filter and applied: https://github.com/iobio/gene.iobio.vue/issues/386
5) New filter doesn't generate variants: https://github.com/iobio/gene.iobio.vue/issues/387
6) Filter popout cut off by bottom of page when launched from clin: https://github.com/iobio/gene.iobio.vue/issues/493

### CODE REVIEW

**Comment by WilliamRichards2017** [comment]
To test:
Verify in Gene - This can be tested on the quarentest build
1. Launch with demo data and let variants load
2. Create a new filter
3. Assign the filter a name
4. Assign the filter Homozygous zygosity
5. Verify that variants pass this filter
6. Verify that the filter correctly displays the name you chose
7. Try to edit the filter to remove all filter attributes, verify that you cannot apply an empty filter

Verify in clin - You will need to do a local install of this PR, and run both gene and clin locally to test inside of clin
1. Launch from demo data and let variants load
2. Pick a variant from the left panel and assign it a significance
3. Without scrolling down, add a custom filter, and assign the zygosity field with homozygous
    - You should be able to click apply, and the popup should not be cut off by the bottom of the page
4. Verify that the significance of the reviewed reviewed did not go away
5. Scroll down until ‘+ New Filter’ is at the very top of the screen
6. Verify that the filter popup is in the same position on the screen as when you were on the top of the page

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://c781aa2d.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://5357aa99.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://39b929c8.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://4f483d54.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
Updated PR to address changes requested:
1) Variants passing custom filters then flagged display custom filter key instead of undefined
2) Adding a second filter no longer overwrites the first filter, as filter keys are now unique, and not all undefined
3) Dissociated consequence dialog box when launched from clin fixed
4) Reviewed variants passing custom filter no longer appear in both lists

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://4038249d.quarantest.iobio.io

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://55b297d8.quarantest.iobio.io

**Comment by WilliamRichards2017** [comment]
These changes allow editing of custom filters.  Custom filter key badge now properly incremented, and null filters removed from geneList.  @adityaekawade Thanks so much for careful checking and finding these issues in my commits!

**Comment by anderspitman** [comment]
quarantest build successful. Demo link at
http://55b297d8.quarantest.iobio.io

**Pull request merged**
